name: isar_flutter_libsx
description: Flutter binaries for the Isar Database. Needs to be included for Flutter apps.
publish_to: 'none'
version: 2.5.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  isarx:
    git:
      url: https://github.com/phonghoang2k/isarx
      path: packages/isar

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libsx
        pluginClass: IsarFlutterLibsXPlugin
      ios:
        pluginClass: IsarFlutterLibsXPlugin
      macos:
        pluginClass: IsarFlutterLibsPlugin
      linux:
        pluginClass: IsarFlutterLibsPlugin
      windows:
        pluginClass: IsarFlutterLibsPlugin
