builders:
  isar_generatorx:
    import: "package:isar_generatorx/isar_generator.dart"
    builder_factories: ["getIsarGenerator"]
    build_extensions: { ".dart": ["isar_generatorx.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
