name: isar_generatorx
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
publish_to: 'none'
version: 2.5.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  isarx:
    git:
      url: https://github.com/phonghoang2k/isarx
      path: packages/isar
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.7.0
  glob: ^2.1.0
  path: ^1.8.2
  dart_style: ^2.2.3
  dartx: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
