name: isarx
description: Fast Cross Platform Database for Flutter Apps. Supports indexes, FTS, queries etc.
version: 2.5.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  js: ^0.6.4
  meta: ^1.8.0

dev_dependencies:
  test: any
  ffigen: any
  lints: any
