name: Dart CI

on: push

jobs:
  drive_ios:
    strategy:
      matrix:
        device:
          - "iPhone 8"
          - "iPhone 11 Pro Max"
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start simulator
        uses: futureware-tech/simulator-action@v1
        with:
          model: ${{ matrix.device }}
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Download binaries
        run: bash tool/download_binaries.sh
        working-directory: packages/isar_flutter_libs
      - name: Run Flutter Driver tests
        run: |
          flutter pub get
          flutter pub run build_runner build
          dart tool/generate_all_tests.dart
          flutter drive --driver=isar_driver.dart --target=isar_driver_target.dart
        working-directory: packages/isar_test

  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29] #[21, 29]
        target: [default]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Download binaries
        run: bash tool/download_binaries.sh
        working-directory: packages/isar_flutter_libs
      - name: Run isar_generator
        run: |
          flutter pub get
          flutter pub run build_runner build
          dart tool/generate_all_tests.dart
        working-directory: packages/isar_test
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          working-directory: packages/isar_test
          script: "flutter drive --driver=isar_driver.dart --target=isar_driver_target.dart"

  drive_desktop:
    strategy:
      matrix:
        os: [macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install Linux requirements
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Download binaries
        run: bash tool/download_binaries.sh
        working-directory: packages/isar_flutter_libs
      - name: Run Flutter Driver tests
        run: |
          flutter pub get
          flutter pub run build_runner build
          dart tool/generate_all_tests.dart
          flutter config --no-enable-web
          flutter config --enable-macos-desktop 
          flutter config --enable-linux-desktop 
          flutter config --enable-windows-desktop 
          flutter drive --driver=isar_driver.dart --target=isar_driver_target.dart
        working-directory: packages/isar_test

  drive_chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install chromedricer
        uses: nanasess/setup-chromedriver@v1
      - name: Prepare chromedricer
        run: chromedriver --port=4444 &
      - name: Run Dart tests in browser
        run: |
          flutter pub get
          flutter pub run build_runner build
          dart tool/generate_all_tests.dart
          flutter drive --driver=isar_driver.dart --target=isar_driver_target.dart -d web-server --browser-name chrome
        working-directory: packages/isar_test

  drive_safari:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Prepare safaridricer
        run: |
          sudo safaridriver --enable
          safaridriver --port=4444 &
      - name: Run Dart tests in browser
        run: |
          flutter pub get
          flutter pub run build_runner build
          dart tool/generate_all_tests.dart
          flutter drive --driver=isar_driver.dart --target=isar_driver_target.dart -d web-server --browser-name safari
        working-directory: packages/isar_test

  drive_firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install geckodriver
        uses: browser-actions/setup-geckodriver@latest
      - name: Prepare geckodriver
        run: geckodriver --port=4444 &
      - name: Run Dart tests in browser
        run: |
          flutter pub get
          flutter pub run build_runner build
          dart tool/generate_all_tests.dart
          flutter drive --driver=isar_driver.dart --target=isar_driver_target.dart -d web-server --browser-name firefox
        working-directory: packages/isar_test
